### ISSUE TITLE
Switch to Docker

### ISSUE THREAD

**Issue by darkstar42** [vision-it/vision-nextcloud#2]
https://github.com/nextcloud/docker

**Comment by martialblog** [comment]
I agree

**Comment by martialblog** [comment]
Ich hab da mal was vorbereitet: 
https://github.com/martialblog/vision-nextcloud

Image wird schon gezogen. TODO: Parameter setzten und Persitent Data einrichten, Container starten.

**Comment by martialblog** [comment]
Hier gibts auch ne fertige docker-compose.yml :taco: 
https://github.com/indiehosters/nextcloud

**Comment by martialblog** [comment]
Würd sagen, alles was wir machen müssen ist: das https://github.com/vision-it/vision-gitlab Profil kopieren/anpassen und dann sollte die Sache laufen.

**Comment by martialblog** [comment]
Hier mal ein erster Wurf: https://github.com/martialblog/vision-nextcloud
Rspec Tests laufen soweit schon. Muss in Vagrant getestet, ggfs. angepasst werden und dann sollte man die Tests erweitert. 

Beaker Test sind wegen Docker in Docker Timeout schwer.

**Comment by martialblog** [comment]
Läuft in Vagrant und hat ne autoconfig.php für NextCloud:
https://github.com/martialblog/vision-nextcloud/commit/ab07f1b1051f02ad0f35fb76daf9e205ec8feeaf

**TODO**:
- Die nginx Config muss noch angepasst werden, HTTPS funktioniert nicht so ganz.

**Comment by martialblog** [comment]
Test gehen klar soweit... nur noch HTTPS und die Sache läuft. https://github.com/martialblog/vision-nextcloud/commit/ef74036da93f604c8e4f1eff71540730a980b713

Cleary I have nothing else to do :shipit:

**Comment by darkstar42** [comment]
Was funktioniert da noch nicht?
Glaub ich musste nur die Reverse Proxy Config anpassen:
https://docs.nextcloud.com/server/9/admin_manual/configuration_server/reverse_proxy_configuration.html

**Comment by martialblog** [comment]
Habs mir noch nicht angeschaut... kann nicht so schwer sein.

**Comment by darkstar42** [comment]
Und macht es nicht auch Sinn die normale Konfiguration anzupassen mittels Puppet? _autoconfig.php_ wird doch afaik nur für die Installation verwendet, d.h. wenn man nachträglich was an den dort enthaltenen Einträgen ändert, wird das nicht in die _config.php_ übernommen?

**Comment by martialblog** [comment]
So wie ich das sehe, ist die config.php nur für die Datenbank Einstellung zuständig. Die restliche Konfig liegt dann dort.

**Comment by darkstar42** [comment]
> If you want to use the SSL proxy during installation you have to create the config/config.php otherwise you have to extend the existing $CONFIG array.

nope ;)

und: 

> ownCloud supports loading configuration parameters from multiple files. You can add arbitrary files ending with .config.php in the config/ directory, for example you could place your email server configuration in email.config.php. This allows you to easily create and manage custom configurations, or to divide a large complex configuration file into a set of smaller files. These custom files are not overwritten by ownCloud, and the values in these files take precedence over config.php.

https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/config_sample_php_parameters.html

d.h. eigentlich fände ich es am besten, wenn wir u.a. ne _proxy.config.php_ und _ldap.config.php_ anlegen.

**Comment by martialblog** [comment]
Ok cool, muss mir mal das Admin Handbuch durchlesen. Find Ich auch gut :+1:

**Comment by martialblog** [comment]
Hab das Repo jetzt hier angelegt: https://github.com/vision-it/vision-nextcloud-docker

**TODO:** 
- [ ] SSL einrichten
- [ ] Restliche Config noch automatisieren (LDAP)

**Comment by martialblog** [comment]
I Know. Will eigentlich das hier löschen aber dann ist unsere schöne Unterhaltung hier weg... Mach Jack hoffentlich dann am Donnerstag..

**Comment by martialblog** [comment]
Hab das alte Zeug auf ne eigene Branch und ne neue production erstellt.

**Comment by martialblog** [comment]
Done and done
